### PR TITLE
Updated index.html with Hans' profile picture

### PR DESCRIPTION
**Pull request by hanskokx**
Signed-off-by: Hans Kokx <hans.d.kokx@gmail.com>

### CODE REVIEW

**Review by Tragikomedia — APPROVED** [review]

**Review by Goober0329 — APPROVED** [review]
All I see is gibberish. Hopefully it's good gibberish.

**Review by Goober0329 — APPROVED** [review]

**Comment by hanskokx** [comment]
> All I see is gibberish. Hopefully it's good gibberish.

If you don't understand it, you can't approve it

**Review by Rift3000 — COMMENTED** [review]
Code looks cleaner and easier to read.

**Comment by Rift3000** [comment]
Hard to find the approved button on mobile

**Pull request merged**
